insert into BANKDEPOSIT (depositId, depositName, depositMinTerm, depositMinAmount, depositCurrency, depositInterestRate, depositAddConditions) values (default,'depositName0',12,100,'usd',4,'condition0');
insert into BANKDEPOSIT (depositId, depositName, depositMinTerm, depositMinAmount, depositCurrency, depositInterestRate, depositAddConditions) values (default,'depositName1',13,200,'eur',5,'condition1');
insert into BANKDEPOSIT (depositId, depositName, depositMinTerm, depositMinAmount, depositCurrency, depositInterestRate, depositAddConditions) values (default,'depositName2',14,300,'usd',6,'condition2');
insert into BANKDEPOSIT (depositId, depositName, depositMinTerm, depositMinAmount, depositCurrency, depositInterestRate, depositAddConditions) values (default,'depositName3',15,400,'usd',7,'condition3');
insert into BANKDEPOSIT (depositId, depositName, depositMinTerm, depositMinAmount, depositCurrency, depositInterestRate, depositAddConditions) values (default,'depositName4',16,500,'grb',8,'condition4');

insert into BANKDEPOSITOR (depositorId,depositorName,depositorDateDeposit,depositorAmountDeposit,depositorAmountPlusDeposit,depositorAmountMinusDeposit,depositorDateReturnDeposit,depositorMarkReturnDeposit,depositId) values (default,'depositorName1','2015-12-01',1001,20,20,'2015-12-02',0,1);
insert into BANKDEPOSITOR (depositorId,depositorName,depositorDateDeposit,depositorAmountDeposit,depositorAmountPlusDeposit,depositorAmountMinusDeposit,depositorDateReturnDeposit,depositorMarkReturnDeposit,depositId) values (default,'depositorName6','2015-12-06',999,60,60,'2015-12-07',0,1);
insert into BANKDEPOSITOR (depositorId,depositorName,depositorDateDeposit,depositorAmountDeposit,depositorAmountPlusDeposit,depositorAmountMinusDeposit,depositorDateReturnDeposit,depositorMarkReturnDeposit,depositId) values (default,'depositorName2','2015-12-02',1002,30,30,'2015-12-03',0,3);
insert into BANKDEPOSITOR (depositorId,depositorName,depositorDateDeposit,depositorAmountDeposit,depositorAmountPlusDeposit,depositorAmountMinusDeposit,depositorDateReturnDeposit,depositorMarkReturnDeposit,depositId) values (default,'depositorName7','2015-12-07',998,70,70,'2015-12-08',0,3);
insert into BANKDEPOSITOR (depositorId,depositorName,depositorDateDeposit,depositorAmountDeposit,depositorAmountPlusDeposit,depositorAmountMinusDeposit,depositorDateReturnDeposit,depositorMarkReturnDeposit,depositId) values (default,'depositorName3','2015-12-03',1003,40,40,'2015-12-09',0,2);
insert into BANKDEPOSITOR (depositorId,depositorName,depositorDateDeposit,depositorAmountDeposit,depositorAmountPlusDeposit,depositorAmountMinusDeposit,depositorDateReturnDeposit,depositorMarkReturnDeposit,depositId) values (default,'depositorName8','2015-12-08',997,80,80,'2015-12-09',0,2);
insert into BANKDEPOSITOR (depositorId,depositorName,depositorDateDeposit,depositorAmountDeposit,depositorAmountPlusDeposit,depositorAmountMinusDeposit,depositorDateReturnDeposit,depositorMarkReturnDeposit,depositId) values (default,'depositorName4','2015-12-04',1004,50,50,'2015-12-05',0,4);
insert into BANKDEPOSITOR (depositorId,depositorName,depositorDateDeposit,depositorAmountDeposit,depositorAmountPlusDeposit,depositorAmountMinusDeposit,depositorDateReturnDeposit,depositorMarkReturnDeposit,depositId) values (default,'depositorName9','2015-12-09',996,90,90,'2015-12-10',0,4);

