//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 01:01:05 AM MSK 
//


package com.brest.bank.util;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bankDepositReport" type="{http://bank.brest.com/soap}bankDepositReport"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bankDepositReport"
})
@XmlRootElement(name = "getBankDepositByIdWithDepositorsResponse")
public class GetBankDepositByIdWithDepositorsResponse {

    @XmlElement(required = true)
    protected BankDepositReport bankDepositReport;

    /**
     * Gets the value of the bankDepositReport property.
     * 
     * @return
     *     possible object is
     *     {@link BankDepositReport }
     *     
     */
    public BankDepositReport getBankDepositReport() {
        return bankDepositReport;
    }

    /**
     * Sets the value of the bankDepositReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankDepositReport }
     *     
     */
    public void setBankDepositReport(BankDepositReport value) {
        this.bankDepositReport = value;
    }

}
