//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 01:01:05 AM MSK 
//


package com.brest.bank.util;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.brest.bank.util package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetBankDepositorsRequest_QNAME = new QName("http://bank.brest.com/soap", "getBankDepositorsRequest");
    private final static QName _GetBankDepositsRequest_QNAME = new QName("http://bank.brest.com/soap", "getBankDepositsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.brest.bank.util
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddBankDepositRequest }
     * 
     */
    public AddBankDepositRequest createAddBankDepositRequest() {
        return new AddBankDepositRequest();
    }

    /**
     * Create an instance of {@link BankDeposit }
     * 
     */
    public BankDeposit createBankDeposit() {
        return new BankDeposit();
    }

    /**
     * Create an instance of {@link GetBankDepositByNameWithDepositorsRequest }
     * 
     */
    public GetBankDepositByNameWithDepositorsRequest createGetBankDepositByNameWithDepositorsRequest() {
        return new GetBankDepositByNameWithDepositorsRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositsFromToMinTermRequest }
     * 
     */
    public GetBankDepositsFromToMinTermRequest createGetBankDepositsFromToMinTermRequest() {
        return new GetBankDepositsFromToMinTermRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositsResponse }
     * 
     */
    public GetBankDepositsResponse createGetBankDepositsResponse() {
        return new GetBankDepositsResponse();
    }

    /**
     * Create an instance of {@link BankDeposits }
     * 
     */
    public BankDeposits createBankDeposits() {
        return new BankDeposits();
    }

    /**
     * Create an instance of {@link UpdateBankDepositRequest }
     * 
     */
    public UpdateBankDepositRequest createUpdateBankDepositRequest() {
        return new UpdateBankDepositRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdFromToDateReturnDepositWithDepositorsResponse }
     * 
     */
    public GetBankDepositByIdFromToDateReturnDepositWithDepositorsResponse createGetBankDepositByIdFromToDateReturnDepositWithDepositorsResponse() {
        return new GetBankDepositByIdFromToDateReturnDepositWithDepositorsResponse();
    }

    /**
     * Create an instance of {@link BankDepositReport }
     * 
     */
    public BankDepositReport createBankDepositReport() {
        return new BankDepositReport();
    }

    /**
     * Create an instance of {@link GetBankDepositByNameFromToDateDepositWithDepositorsResponse }
     * 
     */
    public GetBankDepositByNameFromToDateDepositWithDepositorsResponse createGetBankDepositByNameFromToDateDepositWithDepositorsResponse() {
        return new GetBankDepositByNameFromToDateDepositWithDepositorsResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositByNameResponse }
     * 
     */
    public GetBankDepositByNameResponse createGetBankDepositByNameResponse() {
        return new GetBankDepositByNameResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositsFromToDateDepositRequest }
     * 
     */
    public GetBankDepositsFromToDateDepositRequest createGetBankDepositsFromToDateDepositRequest() {
        return new GetBankDepositsFromToDateDepositRequest();
    }

    /**
     * Create an instance of {@link DeleteBankDepositRequest }
     * 
     */
    public DeleteBankDepositRequest createDeleteBankDepositRequest() {
        return new DeleteBankDepositRequest();
    }

    /**
     * Create an instance of {@link DeleteBankDepositResponse }
     * 
     */
    public DeleteBankDepositResponse createDeleteBankDepositResponse() {
        return new DeleteBankDepositResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositsFromToInterestRateRequest }
     * 
     */
    public GetBankDepositsFromToInterestRateRequest createGetBankDepositsFromToInterestRateRequest() {
        return new GetBankDepositsFromToInterestRateRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositsByInterestRateResponse }
     * 
     */
    public GetBankDepositsByInterestRateResponse createGetBankDepositsByInterestRateResponse() {
        return new GetBankDepositsByInterestRateResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositsByCurrencyResponse }
     * 
     */
    public GetBankDepositsByCurrencyResponse createGetBankDepositsByCurrencyResponse() {
        return new GetBankDepositsByCurrencyResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositorsResponse }
     * 
     */
    public GetBankDepositorsResponse createGetBankDepositorsResponse() {
        return new GetBankDepositorsResponse();
    }

    /**
     * Create an instance of {@link BankDepositors }
     * 
     */
    public BankDepositors createBankDepositors() {
        return new BankDepositors();
    }

    /**
     * Create an instance of {@link AddBankDepositResponse }
     * 
     */
    public AddBankDepositResponse createAddBankDepositResponse() {
        return new AddBankDepositResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositByNameFromToDateReturnDepositWithDepositorsRequest }
     * 
     */
    public GetBankDepositByNameFromToDateReturnDepositWithDepositorsRequest createGetBankDepositByNameFromToDateReturnDepositWithDepositorsRequest() {
        return new GetBankDepositByNameFromToDateReturnDepositWithDepositorsRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositorByNameResponse }
     * 
     */
    public GetBankDepositorByNameResponse createGetBankDepositorByNameResponse() {
        return new GetBankDepositorByNameResponse();
    }

    /**
     * Create an instance of {@link BankDepositor }
     * 
     */
    public BankDepositor createBankDepositor() {
        return new BankDepositor();
    }

    /**
     * Create an instance of {@link GetBankDepositorByIdResponse }
     * 
     */
    public GetBankDepositorByIdResponse createGetBankDepositorByIdResponse() {
        return new GetBankDepositorByIdResponse();
    }

    /**
     * Create an instance of {@link UpdateBankDepositResponse }
     * 
     */
    public UpdateBankDepositResponse createUpdateBankDepositResponse() {
        return new UpdateBankDepositResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdWithDepositorsRequest }
     * 
     */
    public GetBankDepositByIdWithDepositorsRequest createGetBankDepositByIdWithDepositorsRequest() {
        return new GetBankDepositByIdWithDepositorsRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositsFromToDateReturnDepositRequest }
     * 
     */
    public GetBankDepositsFromToDateReturnDepositRequest createGetBankDepositsFromToDateReturnDepositRequest() {
        return new GetBankDepositsFromToDateReturnDepositRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositorByNameRequest }
     * 
     */
    public GetBankDepositorByNameRequest createGetBankDepositorByNameRequest() {
        return new GetBankDepositorByNameRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdFromToDateDepositWithDepositorsRequest }
     * 
     */
    public GetBankDepositByIdFromToDateDepositWithDepositorsRequest createGetBankDepositByIdFromToDateDepositWithDepositorsRequest() {
        return new GetBankDepositByIdFromToDateDepositWithDepositorsRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositByNameRequest }
     * 
     */
    public GetBankDepositByNameRequest createGetBankDepositByNameRequest() {
        return new GetBankDepositByNameRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdFromToDateDepositWithDepositorsResponse }
     * 
     */
    public GetBankDepositByIdFromToDateDepositWithDepositorsResponse createGetBankDepositByIdFromToDateDepositWithDepositorsResponse() {
        return new GetBankDepositByIdFromToDateDepositWithDepositorsResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdResponse }
     * 
     */
    public GetBankDepositByIdResponse createGetBankDepositByIdResponse() {
        return new GetBankDepositByIdResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositsFromToInterestRateResponse }
     * 
     */
    public GetBankDepositsFromToInterestRateResponse createGetBankDepositsFromToInterestRateResponse() {
        return new GetBankDepositsFromToInterestRateResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositByNameFromToDateReturnDepositWithDepositorsResponse }
     * 
     */
    public GetBankDepositByNameFromToDateReturnDepositWithDepositorsResponse createGetBankDepositByNameFromToDateReturnDepositWithDepositorsResponse() {
        return new GetBankDepositByNameFromToDateReturnDepositWithDepositorsResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdRequest }
     * 
     */
    public GetBankDepositByIdRequest createGetBankDepositByIdRequest() {
        return new GetBankDepositByIdRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdFromToDateReturnDepositWithDepositorsRequest }
     * 
     */
    public GetBankDepositByIdFromToDateReturnDepositWithDepositorsRequest createGetBankDepositByIdFromToDateReturnDepositWithDepositorsRequest() {
        return new GetBankDepositByIdFromToDateReturnDepositWithDepositorsRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdWithDepositorsResponse }
     * 
     */
    public GetBankDepositByIdWithDepositorsResponse createGetBankDepositByIdWithDepositorsResponse() {
        return new GetBankDepositByIdWithDepositorsResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositorByIdRequest }
     * 
     */
    public GetBankDepositorByIdRequest createGetBankDepositorByIdRequest() {
        return new GetBankDepositorByIdRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositsFromToDateDepositResponse }
     * 
     */
    public GetBankDepositsFromToDateDepositResponse createGetBankDepositsFromToDateDepositResponse() {
        return new GetBankDepositsFromToDateDepositResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositsFromToDateReturnDepositResponse }
     * 
     */
    public GetBankDepositsFromToDateReturnDepositResponse createGetBankDepositsFromToDateReturnDepositResponse() {
        return new GetBankDepositsFromToDateReturnDepositResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositByNameFromToDateDepositWithDepositorsRequest }
     * 
     */
    public GetBankDepositByNameFromToDateDepositWithDepositorsRequest createGetBankDepositByNameFromToDateDepositWithDepositorsRequest() {
        return new GetBankDepositByNameFromToDateDepositWithDepositorsRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositsByInterestRateRequest }
     * 
     */
    public GetBankDepositsByInterestRateRequest createGetBankDepositsByInterestRateRequest() {
        return new GetBankDepositsByInterestRateRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositsByCurrencyRequest }
     * 
     */
    public GetBankDepositsByCurrencyRequest createGetBankDepositsByCurrencyRequest() {
        return new GetBankDepositsByCurrencyRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositByNameWithDepositorsResponse }
     * 
     */
    public GetBankDepositByNameWithDepositorsResponse createGetBankDepositByNameWithDepositorsResponse() {
        return new GetBankDepositByNameWithDepositorsResponse();
    }

    /**
     * Create an instance of {@link GetBankDepositsFromToMinTermResponse }
     * 
     */
    public GetBankDepositsFromToMinTermResponse createGetBankDepositsFromToMinTermResponse() {
        return new GetBankDepositsFromToMinTermResponse();
    }

    /**
     * Create an instance of {@link BankDepositsReport }
     * 
     */
    public BankDepositsReport createBankDepositsReport() {
        return new BankDepositsReport();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bank.brest.com/soap", name = "getBankDepositorsRequest")
    public JAXBElement<Object> createGetBankDepositorsRequest(Object value) {
        return new JAXBElement<Object>(_GetBankDepositorsRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bank.brest.com/soap", name = "getBankDepositsRequest")
    public JAXBElement<Object> createGetBankDepositsRequest(Object value) {
        return new JAXBElement<Object>(_GetBankDepositsRequest_QNAME, Object.class, null, value);
    }

}
