//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 01:57:40 AM MSK 
//


package com.brest.bank.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.brest.bank.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetBankDepositsRequest_QNAME = new QName("http://bank.brest.com/soap", "getBankDepositsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.brest.bank.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBankDepositorByIdResponse }
     * 
     */
    public GetBankDepositorByIdResponse createGetBankDepositorByIdResponse() {
        return new GetBankDepositorByIdResponse();
    }

    /**
     * Create an instance of {@link BankDepositor }
     * 
     */
    public BankDepositor createBankDepositor() {
        return new BankDepositor();
    }

    /**
     * Create an instance of {@link GetBankDepositsResponse }
     * 
     */
    public GetBankDepositsResponse createGetBankDepositsResponse() {
        return new GetBankDepositsResponse();
    }

    /**
     * Create an instance of {@link BankDeposits }
     * 
     */
    public BankDeposits createBankDeposits() {
        return new BankDeposits();
    }

    /**
     * Create an instance of {@link GetBankDepositorByIdRequest }
     * 
     */
    public GetBankDepositorByIdRequest createGetBankDepositorByIdRequest() {
        return new GetBankDepositorByIdRequest();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdResponse }
     * 
     */
    public GetBankDepositByIdResponse createGetBankDepositByIdResponse() {
        return new GetBankDepositByIdResponse();
    }

    /**
     * Create an instance of {@link BankDeposit }
     * 
     */
    public BankDeposit createBankDeposit() {
        return new BankDeposit();
    }

    /**
     * Create an instance of {@link GetBankDepositByIdRequest }
     * 
     */
    public GetBankDepositByIdRequest createGetBankDepositByIdRequest() {
        return new GetBankDepositByIdRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bank.brest.com/soap", name = "getBankDepositsRequest")
    public JAXBElement<Object> createGetBankDepositsRequest(Object value) {
        return new JAXBElement<Object>(_GetBankDepositsRequest_QNAME, Object.class, null, value);
    }

}
