insert into BANKDEPOSITOR (depositorId,
                        depositorName,
						depositorDateDeposit,
						depositorAmountDeposit,
						depositorAmountPlusDeposit,
						depositorAmountMinusDeposit,
						depositorDateReturnDeposit,
						depositorMarkReturnDeposit,
						depositId)
values (:depositorId,
        :depositorName,
        :depositorDateDeposit,
        :depositorAmountDeposit,
        :depositorAmountPlusDeposit,
        :depositorAmountMinusDeposit,
		:depositorDateReturnDeposit,
		:depositorMarkReturnDeposit,
		:depositId)